import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: "https://www.gamaex.cl",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 1,
    },
    {
      url: "https://www.gamaex.cl/cambiar-dolares-providencia",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/money-exchange-santiago",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/casa-de-cambio-providencia",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/cambio-de-moneda-santiago",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/comprar-dolares-santiago",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/vender-dolares-santiago",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/cambiar-euros-santiago",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/cambiar-reales-santiago",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/transferencias-internacionales-chile",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl/casa-de-cambio-santiago",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/casa-de-cambio-las-condes",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/casa-de-cambio-vitacura",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl/casa-de-cambio-nunoa",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl/casa-de-cambio-metro-pedro-de-valdivia",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/precio-dolar-hoy-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/precio-euro-hoy-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/cotizacion-dolar-online",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/calculadora-divisas-chile",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/cambio-real-brasileno-hoy",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl/currency-exchange-near-me-santiago",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/tipo-de-cambio-hoy-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/cambio-libra-esterlina-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl/cambio-franco-suizo-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl/gamaex-chile-opiniones",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl/cambio-yen-japones-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl/cambio-peso-argentino-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl/cambio-dolar-canadiense-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl/cambio-dolar-australiano-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl/vender-euros-santiago",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/comprar-euros-santiago",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/precio-dolar-santiago-hoy",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/cambio-euro-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/comprar-dolares-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/vender-dolares-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/casa-de-cambio-barrio-italia",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.gamaex.cl/cotizacion-euro-online",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/cambio-moneda-extranjera-chile",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/mejor-tipo-de-cambio-santiago",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/cambio-dolar-hoy-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/casa-de-cambio-miraflores",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.gamaex.cl/casa-de-cambio-el-bosque",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.gamaex.cl/casa-de-cambio-tobalaba",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl/casa-de-cambio-metro-los-leones",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/casa-de-cambio-metro-manuel-montt",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl/comprar-dolares-providencia",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/vender-dolares-providencia",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/cuanto-vale-el-dolar-hoy",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/precio-dolar-hoy-providencia",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/comprar-euros-providencia",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/vender-euros-providencia",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/cambio-divisas-las-condes",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl/cambio-divisas-santiago-centro",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl/exchange-rate-chile-today",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/cambiar-euros-a-pesos-chilenos",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/tipo-de-cambio-euro-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/cambio-peso-colombiano-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.75,
    },
    {
      url: "https://www.gamaex.cl/cambio-sol-peruano-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.75,
    },
    {
      url: "https://www.gamaex.cl/casa-de-cambio-metro-tobalaba",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/casa-de-cambio-metro-irarrazaval",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.gamaex.cl/comprar-libras-esterlinas-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl/comprar-reales-brasilenios-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl/tipo-de-cambio-dolar-hoy-santiago",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/precio-euro-hoy-providencia",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/casas-de-cambio-providencia",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/cambio-divisas-online-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl/casa-de-cambio-pedro-de-valdivia",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/comprar-dolares-sin-comision",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/cotizacion-dolar-euro-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/gamaex-providencia",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl/comprar-yenes-japoneses-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.75,
    },
    {
      url: "https://www.gamaex.cl/cambio-moneda-viaje-chile",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl/efectivo-en-moneda-extranjera-chile",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.gamaex.cl/casa-de-cambio-metro-baquedano",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.gamaex.cl/casa-de-cambio-metro-santa-isabel",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.gamaex.cl/cuanto-esta-el-dolar-en-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/cambiar-dolares-a-pesos-chilenos",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/precio-euro-hoy-santiago",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/tipo-de-cambio-dolar-hoy-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/cambio-divisas-providencia",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/cuanto-vale-el-euro-en-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/cambiar-reales-a-pesos-chilenos",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/cambio-dolar-peso-chileno",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/cambio-de-dolares-hoy-santiago",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/best-exchange-rate-santiago",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/where-to-exchange-money-santiago",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl/casa-de-cambio-costanera-center",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.gamaex.cl/cotizacion-dolar-chile-hoy",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: "https://www.gamaex.cl/cambio-corona-noruega-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.75,
    },
    {
      url: "https://www.gamaex.cl/cambio-yuan-chino-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.75,
    },
    {
      url: "https://www.gamaex.cl/pago-proveedores-moneda-extranjera",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl/cambio-divisas-sin-comision",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/conversor-divisas-chile",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl/cambio-dolar-euro-santiago",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.85,
    },
    {
      url: "https://www.gamaex.cl#tasas",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: "https://www.gamaex.cl#servicios",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.6,
    },
    {
      url: "https://www.gamaex.cl#faq",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://www.gamaex.cl#ubicacion",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
    },
  ];
}
